[tool.black]
line-length = 79
target-version = ['py39']
skip-string-normalization = false
skip-magic-trailing-comma = false
color = true
verbose = true
exclude = '''
/(
    migrations
  | tests
  | __pycache__
  | venv
  | \.git
)/
'''

[tool.isort]
profile = "black"
line_length = 79
force_sort_within_sections = false
force_single_line = false
combine_as_imports = false
lines_between_types = 1
order_by_type = true
no_lines_before = "LOCALFOLDER"
force_to_top = "stdlib"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
import_heading_stdlib = ""
import_heading_thirdparty = ""
import_heading_firstparty = ""
import_heading_localfolder = ""
force_alphabetical_sort_within_sections = false
lexicographical = false
honor_noqa = true
skip = [
    "cms/models/__init__.py",
    "cms/serializers/__init__.py",
]
skip_glob = [
    "**/__init__.py"
]
