# Generated by Django 4.2.20 on 2025-04-19 19:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationTierRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tiers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("TIER1", "TIER1"),
                                ("TIER2", "TIER2"),
                                ("TIER3", "TIER3"),
                            ],
                            max_length=5,
                        ),
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MinCartValueRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_value", models.FloatField()),
                ("max_discount", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethodRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "methods",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("CC", "Credit Card"),
                                ("DC", "Debit Card"),
                                ("UPI", "UPI"),
                                ("COD", "Cash on Delivery"),
                            ],
                            max_length=5,
                        ),
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPriorityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "priorities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (1, "Platinum"),
                                (2, "Gold"),
                                (3, "Silver"),
                            ],
                        ),
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="campaign",
            name="discount_target",
            field=models.CharField(
                choices=[
                    ("CART", "Cart Value Discount"),
                    ("DELIVERY", "Delivery Fee Discount"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("PERCENTAGE", "Discount as percentage of value"),
                    ("FIXED", "Discount as fixed amount"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="CampaignRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="cms.campaign",
                        verbose_name="Associated Campaign",
                    ),
                ),
                (
                    "location_rules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaigns",
                        to="cms.locationtierrule",
                    ),
                ),
                (
                    "min_cart_rule",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_rule",
                        to="cms.mincartvaluerule",
                    ),
                ),
                (
                    "payment_rules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaigns",
                        to="cms.paymentmethodrule",
                    ),
                ),
                (
                    "priority_rules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaigns",
                        to="cms.userpriorityrule",
                    ),
                ),
            ],
        ),
    ]
