# Generated by Django 4.2.20 on 2025-04-19 20:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cms",
            "0002_locationtierrule_mincartvaluerule_paymentmethodrule_and_more",  # noqa
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
