# Generated by Django 4.2.20 on 2025-04-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_alter_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customergroup",
            name="members",
            field=models.ManyToManyField(
                related_name="groups", to="cms.customer"
            ),
        ),
        migrations.DeleteModel(
            name="GroupMembership",
        ),
    ]
