# Generated by Django 4.2.20 on 2025-04-19 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_customergroup_members_delete_groupmembership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignrules",
            name="location_rules",
        ),
        migrations.AlterField(
            model_name="campaignrules",
            name="min_cart_rule",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mincart_campaigns",
                to="cms.mincartvaluerule",
            ),
        ),
        migrations.RemoveField(
            model_name="campaignrules",
            name="payment_rules",
        ),
        migrations.RemoveField(
            model_name="campaignrules",
            name="priority_rules",
        ),
        migrations.AddField(
            model_name="campaignrules",
            name="location_rules",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_campaigns",
                to="cms.locationtierrule",
            ),
        ),
        migrations.AddField(
            model_name="campaignrules",
            name="payment_rules",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_campaigns",
                to="cms.paymentmethodrule",
            ),
        ),
        migrations.AddField(
            model_name="campaignrules",
            name="priority_rules",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="priority_campaigns",
                to="cms.userpriorityrule",
            ),
        ),
    ]
