# Generated by Django 4.2.20 on 2025-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_remove_campaignrules_location_rules_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="campaignusage",
            name="cms_campaig_custome_f6dfac_idx",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="budget_used",
        ),
        migrations.RemoveField(
            model_name="campaignusage",
            name="cart_id",
        ),
        migrations.RemoveField(
            model_name="campaignusage",
            name="order_id",
        ),
        migrations.AddField(
            model_name="campaignusage",
            name="idempotent_key",
            field=models.UUIDField(default=2, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="campaignusage",
            index=models.Index(
                fields=["campaign", "customer"],
                name="cms_campaig_campaig_32f549_idx",
            ),
        ),
    ]
