# Generated by Django 4.2.20 on 2025-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cms",
            "0006_remove_campaignusage_cms_campaig_custome_f6dfac_idx_and_more",  # noqa
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignusage",
            name="idempotent_key",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
