# Generated by Django 4.2.20 on 2025-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_alter_campaignusage_idempotent_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignusage",
            name="idempotent_key",
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
