# Generated by Django 4.2.20 on 2025-04-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_alter_campaignusage_idempotent_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignusage",
            name="id",
        ),
        migrations.AlterField(
            model_name="campaignusage",
            name="idempotent_key",
            field=models.UUIDField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
