# Generated by Django 4.2.20 on 2025-04-20 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0010_remove_campaignusage_id_and_more"),
    ]

    operations = []
