# Generated by Django 4.2.20 on 2025-04-20 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_campaignusage_id_alter_campaignusage_idempotent_key"),
    ]

    operations = []
