# Generated by Django 4.2.20 on 2025-04-20 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0012_alter_campaignusage_idempotent_key"),
    ]

    operations = []
